apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: falcon-backend
  template:
    metadata:
      labels:
        app: falcon-backend
    spec:
      containers:
      - name: falcon-backend
        image: yourusername/falcon-backend
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_URL
