---
- name: Install nginx
  apt:
    name: nginx
    state: present
  notify: Start nginx

- name: Forward requests from port 80 to container
  template:
    src: nginx-conf.j2
    dest: /etc/nginx/sites-available/default

  handlers:
    - name: Start nginx
      service:
        name: nginx
        state: restarted
