pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout source code
                checkout scm
            }
        }
        stage('Provision EC2 Users') {
            steps {
                script {
                    // Run Ansible playbook
                    ansiblePlaybook(
                        credentialsId: 'ansible-credentials',
                        inventory: './inventory.ini',
                        playbook: './provision_users.yml'
                    )
                }
            }
        }
    }
}
