pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout source code
                checkout scm
            }
        }
        stage('Provision EC2 Users') {
            steps {
                script {
                    // Run Ansible playbook
                    ansiblePlaybook(
                        credentialsId: 'your_ssh_key_credentials_id',
                        inventory: 'path_to_inventory.ini',
                        playbook: 'path_to_provision_users.yml'
                    )
                }
            }
        }
    }
}
